/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package analytics.google;

import com.google.analytics.tracking.android.Tracker;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;

import java.util.HashMap;
import java.lang.Long;

// This proxy can be created by calling GoogleAnalytics.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=GoogleAnalyticsModule.class)
public class TrackerProxy extends KrollProxy
{
	// Standard Debugging variables
	private static final String LCAT = "TrackerProxy";
	private static final boolean DBG = TiConfig.LOGD;

	private Tracker tracker;

	// Constructor
	public TrackerProxy(Tracker t)
	{
		super();

		tracker = t;
	}

	@Kroll.method
	public void trackEvent(HashMap props)
	{
		KrollDict propsDict = new KrollDict(props);
		String category = TiConvert.toString(propsDict, "category");
		String action = TiConvert.toString(propsDict, "action");
		String label = TiConvert.toString(propsDict, "label");
		long value = TiConvert.toInt(propsDict, "value");
		tracker.sendEvent(category, action, label, value);
	}

	@Kroll.method
	public void trackScreen(String screen)
	{
		tracker.sendView(screen);
	}

	@Kroll.method
	public void trackTiming(HashMap props)
	{
		KrollDict propsDict = new KrollDict(props);
		String category = TiConvert.toString(propsDict, "category");
		String name = TiConvert.toString(propsDict, "name");
		String label = TiConvert.toString(propsDict, "label");
		long interval = TiConvert.toInt(propsDict, "time");
		tracker.sendTiming(category, interval, name, label);
	}

	@Kroll.method
	public void trackSocial(HashMap props)
	{
		KrollDict propsDict = new KrollDict(props);
		String network = TiConvert.toString(propsDict, "network");
		String action = TiConvert.toString(propsDict, "action");
		String target = TiConvert.toString(propsDict, "target");
		tracker.sendSocial(network, action, target);
	}

	@Kroll.method
	public void trackTransaction(TransactionProxy tp)
	{
		tracker.sendTransaction(tp.transaction);
	}
}